[build]
# pre_cmdを修正
pre_cmd = []  # 空にする

# GOPATHの設定を変更
cmd = "go build -o ./tmp/main ."  # GOPATHの指定を削除

# tmpディレクトリの設定
tmp_dir = "tmp"

# バイナリの設定
bin = "tmp/main"

# 除外設定を確認
exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]