volumes:
  postgres-data:
  pgadmin-data:
  next-node-modules:
  postgres-test-data:

services:
  backend:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
    networks:
      - dev-network
    command: sleep infinity

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    env_file:
      - .env
    user: vscode
    volumes:
      - ../..:/workspaces:cached
      - next-node-modules:/workspaces/frontend/node_modules
    networks:
      - dev-network
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    env_file:
      - .env
    networks:
      - dev-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "password_encryption=md5"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - dev-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json

  test-db:
    container_name: test-postgres-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - dev-network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
      - "-c"
      - "log_connections=on"
      - "-c"
      - "password_encryption=md5"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"

networks:
  dev-network:
    driver: bridge
